"""chat context prompts

Revision ID: d2b1e5ed3c63
Revises: 5271d29a5674
Create Date: 2024-08-23 20:56:54.784941

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d2b1e5ed3c63"
down_revision = "5271d29a5674"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_context_prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_context_prompts")),
    )
    op.create_index(
        op.f("ix_chat_context_prompts_id"),
        "chat_context_prompts",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_context_prompts_id"), table_name="chat_context_prompts")
    op.drop_table("chat_context_prompts")
    # ### end Alembic commands ###
