"""
Constants used throughout the codebase
"""

PRODUCTION = "PRODUCTION"
DEVELOPMENT = "DEVELOPMENT"
TESTING = "TESTING"

MINIMUM_PASSWORD_LENGTH = 4

AUTH_TOKEN_NAME = "access_token"
ACCESS_TOKEN_EXPIRY_DAYS = 7
